pipeline {
    agent any
        tools {
        jdk 'JAVA'
        maven 'maven'
    }
    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }
        stages {
        stage("Git Checkout") {
            steps {
                git branch:'main', changelog:false, poll:false,url:'https://github.com/KelerMC/ProyectoFinalV-VG4'
            }
        }
        stage("Build with Maven") {
            steps {
                bat "mvn -f spring-petclinic-main clean compile"
            }
        }
        stage("SonarQube Analysis ") {
            steps {
                bat "$SCANNER_HOME/bin/sonar-scanner -Dsonar.url=http://localhost:9000/ \
                    -Dsonar.login=squ_f98ffa7978805dd40117bf4113272c66f6164f59 \
                    -Dsonar.projectKey=ProyectoFinal \
                    -Dsonar.projectName=ProyectoFinal \
                    -Dsonar.sources=. \
                    -Dsonar.java.binaries=."
            }
        }
        // And next stages if you want to define further...
    } // End of stages
} // End of pipeline